name: Linter
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint --max-warnings 0
