name: Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install modules
        run: yarn
      - name: Run tests
        env:
          NODE_ENV: ci
        run: yarn test
